wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713633081.0
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      - 31
      - 37
      4: 3.10.14
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
early_stopping_rounds:
  desc: null
  value: 20
gamma:
  desc: null
  value: 0.8683335727642567
learning_rate:
  desc: null
  value: 0.5907194821047945
min_child_weight:
  desc: null
  value: 78
n_estimators:
  desc: null
  value: 494
