wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713633133.0
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 31
      - 37
      4: 3.10.14
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
    visualize:
      Feature Importance:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: Feature
            value: Importance
          stringSettings:
            title: Feature Importance
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Feature Importance_table
                fields: []
    m:
    - 1: validation_0-rmse
      6:
      - 3
      7:
      - 1
early_stopping_rounds:
  desc: null
  value: 20
gamma:
  desc: null
  value: 0.8683335727642567
learning_rate:
  desc: null
  value: 0.5907194821047945
min_child_weight:
  desc: null
  value: 78
n_estimators:
  desc: null
  value: 494
learner:
  desc: null
  value:
    generic_param:
      device: cuda:0
      fail_on_invalid_gpu_id: '0'
      n_jobs: '0'
      nthread: '0'
      random_state: '0'
      seed: '0'
      seed_per_iteration: '0'
      validate_parameters: '1'
    gradient_booster:
      gbtree_model_param:
        num_parallel_tree: '1'
        num_trees: '0'
      gbtree_train_param:
        process_type: default
        tree_method: gpu_hist
        updater: grow_gpu_hist
        updater_seq: grow_gpu_hist
      name: gbtree
      specified_updater: false
      tree_train_param:
        alpha: '0'
        cache_opt: '1'
        colsample_bylevel: '1'
        colsample_bynode: '1'
        colsample_bytree: '1'
        eta: '0.300000012'
        gamma: '0'
        grow_policy: depthwise
        interaction_constraints: ''
        lambda: '1'
        learning_rate: '0.300000012'
        max_bin: '256'
        max_cat_threshold: '64'
        max_cat_to_onehot: '4'
        max_delta_step: '0'
        max_depth: '6'
        max_leaves: '0'
        min_child_weight: '1'
        min_split_loss: '0'
        monotone_constraints: ()
        refresh_leaf: '1'
        reg_alpha: '0'
        reg_lambda: '1'
        sampling_method: uniform
        sketch_ratio: '2'
        sparse_threshold: '0.20000000000000001'
        subsample: '1'
      updater:
      - hist_train_param:
          debug_synchronize: '0'
          max_cached_hist_node: '65536'
        name: grow_gpu_hist
    learner_model_param:
      base_score: 5E-1
      boost_from_average: '1'
      num_class: '0'
      num_feature: '26'
      num_target: '1'
    learner_train_param:
      booster: gbtree
      disable_default_eval_metric: '0'
      multi_strategy: one_output_per_tree
      objective: reg:squarederror
    metrics:
    - name: rmse
    objective:
      name: reg:squarederror
      reg_loss_param:
        scale_pos_weight: '1'
version:
  desc: null
  value:
  - 2
  - 0
  - 3
