wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713632612.0
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      - 31
      4: 3.10.14
      5: 0.16.6
      8:
      - 1
      - 5
      13: linux-x86_64
